# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90cf8e0c8dff235cea712b3f1d76e4b34a4af23e040e8a8af6e431fb8b0cfb97a059a4615c6b59cdc55050fffb28e634190e6ec1f9056b3bf6d6ed23be337d35

test:
  secret_key_base: 5fd2513ad0cd8e50dda4bf0d3e498dc2cf357ca684f7d68e4df1bb1856d47480fa593c49498e05c1633221a5fdeb3952fa5997a81245f542817002f40f0b9e46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
